import os
import shutil
import uuid
from pathlib import Path
from typing import Dict
from database.undo_repository import log_operation

class FileOrganizer:
    def __init__(self, base_path: str, log_callback=None):
        self.base_path = Path(base_path)
        self.log = log_callback if log_callback else print

    def generate_unique_filename(self, target_path: Path) -> Path:
        """
        If a file already exists at target_path, generate a new name.
        Example: file.pdf -> file_1.pdf -> file_2.pdf
        """
        if not target_path.exists():
            return target_path
            
        base = target_path.stem
        ext = target_path.suffix
        directory = target_path.parent
        
        counter = 1
        while True:
            new_name = f"{base}_{counter}{ext}"
            new_path = directory / new_name
            if not new_path.exists():
                return new_path
            counter += 1

    def apply_organization(self, tree_data: Dict):
        """
        Takes the JSON tree data generated by the PreviewBuilder and executes the organization.
        """
        self.batch_id = str(uuid.uuid4())
        self.parse_and_move(tree_data, self.base_path)
        return self.batch_id

    def parse_and_move(self, node, current_path: Path):
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "_files":
                    for file_info in value:
                        self.move_file(file_info.get("path"), current_path)
                else:
                    folder_path = current_path / key
                    self.log(f"> mkdir \"{folder_path}\"")
                    folder_path.mkdir(parents=True, exist_ok=True)
                    self.parse_and_move(value, folder_path)
        elif isinstance(node, list):
            for file_info in node:
                self.move_file(file_info.get("path"), current_path)
                    
    def move_file(self, source_file, current_path: Path):
        if not source_file:
            return
            
        source_path = Path(source_file)
        
        if source_path.exists() and source_path.is_file():
            destination_path = current_path / source_path.name
            
            if source_path.resolve() != destination_path.resolve():
                # Make sure destination is unique so we don't overwrite
                destination_path = self.generate_unique_filename(destination_path)
                self.log(f"> move \"{source_path.name}\" \"{destination_path}\"")
                shutil.move(str(source_path), str(destination_path))
                log_operation(str(source_path), str(destination_path), self.batch_id)
        else:
            self.log(f"! File not found: {source_path}")
